// Do not edit. This file is machine generated by the Resource DLL Wizard.

library test;

{ITE} {LCID:00000804:00000404} {}
{ITE} {DFMFileType} {UntAbout.dfm}
{ITE} {DFMFileType} {UntTest.dfm}
{ITE} {RCFileType} {test_DRC.rc}

{$R 'UntAbout.dfm' FrmAbout:TForm}
{$R 'UntTest.dfm' FrmTest:TForm}
{$R 'test_DRC.res' 'test_DRC.rc'}

{$E CHT}

begin
end.